### ISSUE TITLE
Unable to View the Tech Club Logo when viewed in Light Mode

### ISSUE THREAD

**Issue by cr2007** [Tech-club/Tech-Club-Blog#12]
When viewed in light mode, the Tech Club logo isn't visible as the same logo used for Dark Mode is being used for Light Mode as well.

![gif (2)](https://user-images.githubusercontent.com/73425927/120431951-41191c80-c38a-11eb-8009-4138d4d41e8c.gif)

**Comment by mk210** [comment]
Reviewed bug @Akilan1999 .
HW Tech Club's logo in the SVG format is required to make this possible. 
@amoghsrivastava Can you share the SVG files of the tech club logo.

**Comment by cr2007** [comment]
@mk210, @amoghsrivastava
> HW Tech Club's logo in the SVG format is required to make this possible.

Is there any way as such where you can directly invert the existing image file provided?
Like something along the lines of
```css
.normal {
    filter:invert(0%)
}
.inverted {
    filter:invert(%100)
}
```

**Comment by mk210** [comment]
> @mk210, @amoghsrivastava
> > HW Tech Club's logo in the SVG format is required to make this possible.
> 
> Is there any way as such where you can directly invert the existing image file provided?
> Like something along the lines of
> `.normal {`
> `        filter:invert(0%)`
> `}`
> `.inverted {`
>         `filter:invert(%100)`
> `}`
> 

Well, not really because it's a Hugo template and I can't find the code which triggers the change in theme! If we can find that, then the above code makes sense!

If we have an SVG instead of a standard PNG format, the theme can change the color when a theme change is triggered.

**Comment by amoghsrivastava** [comment]
@mk210 https://drive.google.com/drive/folders/1UmN-EK67-9YH_BnHKTQdVtBJBB4dwOgp?usp=sharing

You can access the logos from here

**Comment by mk210** [comment]
Just pushed some code changes which will change the fill color when toggling between themes.
