### ISSUE TITLE
When creating new blog in the admin panel 

### ISSUE THREAD

**Issue by Akilan1999** [Tech-club/Tech-Club-Blog#2]
## Error 
Failed to persist entry: API_ERROR: Although you appear to have the correct authorization credentials, the `HWTechClub` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/

A fix for this would be great

**Comment by benjaminjacobreji** [comment]
It was a permission error in regards to GitHub and third party access.
Fixed it now.
Closing this issue.
If issue persists, reopen this issue and notify me please.
